version: 2.1

jobs:
    build:
        docker:
            - image: ryanpedersen42/deno-base:0.0.1
        steps:
            - checkout
            - run: deno test

workflows:
    build_test_deploy:
        jobs:
            - build 