version: 2.1

jobs:
    build:
        docker:
            - image: ryanpedersen42/deno-base:0.1.0
        steps:
            - checkout
            - restore_cache:
                key: dependencies
                paths:
                    - dependencies.ts
            - run: deno cache dependencies.ts
            - save_cache:
                key: dependencies
                paths:
                    - dependencies.ts
            - run: 
                command: |
                    TESTFILES=$(circleci tests glob "__tests__/**.ts" | circleci tests split --split-by=timings)
                    deno test $TESTFILES

workflows:
    build_test_deploy:
        jobs:
            - build 