version: 2.1

jobs:
    build:
        docker:
            - image: ryanpedersen42/deno-base-image:latest
        steps:
            - checkout
            - run: echo "export DENO_DIR=$PWD/deps" >> $BASH_ENV
            - restore_cache:
                key: v2-{{ checksum "$DENO_DIR/dependencies.ts" }}
                paths:
                    - dependencies/dependencies.ts
            - run: deno cache dependencies.ts
            - save_cache:
                key: v2-{{ checksum "$DENO_DIR/dependencies.ts" }}
                paths:
                    - dependencies/dependencies.ts
            - run: deno test
workflows:
    build_test_deploy:
        jobs:
            - build 