version: 2.1

jobs:
    build:
        docker:
            - image: ryanpedersen42/deno-base-image:latest
        steps:
            - checkout
            - restore_cache:
                key: dependencies
                paths:
                    - ~/deps/dependencies.ts
            - run: deno cache dependencies.ts
            - save_cache:
                key: dependencies
                paths:
                    - ~/deps/dependencies.ts
            - run: deno test

workflows:
    build_test_deploy:
        jobs:
            - build 