version: 2.1

jobs:
    build:
        docker:
            - image: ryanpedersen42/deno-base:0.0.1
        steps:
            - checkout
            - restore_cache:
                key: dependencies
                paths:
                    - dependencies.ts
            - run: deno cache dependencies.ts
            - save_cache:
                key: dependencies
                paths:
                    - dependencies.ts
            - run: deno test

workflows:
    build_test_deploy:
        jobs:
            - build 